### ISSUE TITLE
ubuntu 12.04 installer test

### ISSUE THREAD

**Issue by trojanspike** [zpanel/installers#13]
I done an install on a vagrant VM
zpanel_12.04ubuntu32

![Installer error](https://s3-eu-west-1.amazonaws.com/bucket-hy87/Selection_004.png)

this is after full install of 10_1_1.sh

**Comment by trojanspike** [comment]
Same problem with 64bit ubuntu 12.04

![](https://s3-eu-west-1.amazonaws.com/bucket-hy87/Selection_005.png)

Seems to be happening here on the install process

Can someone look at this pref who wrote the installer script and test it in the VM
@andykimpe

**Comment by stokes84** [comment]
Hmm, I see the issue. in `/etc/zpanel/panel/cnf/db.php` and `/etc/zpanel/panel/cnf/security.php` we've got default values from the git repo. 

For example in `security.php` after install we have..
`$security['server_crypto_key'] = "GENERATED_SALT_HERE";`

and in db.php after install we got...
`
$host = 'localhost';
$dbname = 'zpanel_core';
$user = 'root';
$pass = 'YOUR_ROOT_MYSQL_PASSWORD';
`
Edit; Deff a mysql issue, fixable with some time

**Comment by trojanspike** [comment]
These broken installers are on the main website, should they be? hrrmmmm
They need to be tested ( install & upgrade ) before deployment

**Comment by allebb** [comment]
I'm really confused with how this can be happening? - Our testing on the
supported OSes did not manage to replicate these issues... Obviously the
installer however is NOT replacing the placeholder values!

**Comment by allebb** [comment]
Lee can you provide details as to what OS and version you are using please
buddy? - Is your OS a VPS provider image (eg. Xen provisioned?)

**Comment by trojanspike** [comment]
these were installed on the vagrant boxes : precise32/64.
I also tried it on an EC2 : Ubuntu 12.04.4 LTS

Same errors , there's a misspelling on the
 service mysql start , which is  service mysqld start in the installer script.
Still other errors show up when I fixed the spelling mistake
