### ISSUE TITLE
BLANK WHITE SCREEN

### ISSUE THREAD

**Issue by ghost** [zpanel/installers#29]
after Updating zpanelx 10.1.0 to 10.1.1 online for centos 6.x
yes checked evrything twice when updating
added a new client and when hit save went to blank white screen ?

**Comment by ghost** [comment]
also not sending email so basically after updating it useless

**Comment by jacobgelling** [comment]
Please post this on the ZPanel forum as this issue tracker isn't used for support.

**Comment by ghost** [comment]
This should be closed. Support should be on forum PLEASE.

Even if you have bugs always better to report to forum before rushing to log it here.

**Comment by ghost** [comment]
This was 2 weeks ago. I made a mistake in reporting here and look above jacob830 already told me.
It was my mistake READING THE DOCS. Told me that all bugs will now be reported via GIT HUB. NOT my fault the forum is a mess. OUTDATED HOWTOs.
I'm new to ZPanel & you guys have createda wickedly good cPanel
My two CENTs for what Its worth would be to take the time to go through FIRST. the forum HOW TOs and remove the OUTDATED ones or the ones where people are left hanging with problems. I don't know if the way the forum is. Is to put of newbies  off. Or if its just NO ONE CAN BE BOTHERED. I've said this before. I know how hard It can be to run a forum. Back in 2003-2005 I had a forum with 60,000 active members all asking questions that had been asked before. What we did as a team was thought of all the silly questions and made a FORUM for TUTORIALS or HOW TOs and made them CLOSED. Because the expertise you guys have got between you, you have probably run into every problem possible. you could always end the how to with a "please post a thread in the PROBLEMS WITH HOW TOs/TUTORIALS linking this thread in your post" I don't have all the  answers thats why I ask Questions. You don't learn If you don't ask. A wise man once said to me there is no such thing as a stupid question ????? ONLY A STUPID answer

**Comment by ghost** [comment]
Closing. USE THE FORUMS FOR SUPPORT.

This is not a bug not an issue and the support team will be happy to reply @:

http://forums.zpanelcp.com/

THANKS
