### ISSUE TITLE
ubuntu 12.04test

### ISSUE THREAD

**Issue by ghostry** [zpanel/installers#34]
1,Wait a very long time and there is no progress Tip.
2,x_profiles.ud_language_vc Field length is too short。
3,utf8 latin1 recommended replaced

**Comment by ghost** [comment]
Use the forums for support and in english.

**Comment by jacobgelling** [comment]
Erm it is in English haha :smile: 

Why UTF8 Latin vs UTF8? - remember ZPanel supports a array of different languages, including ones with cyrillic alphabet and so on.

**Comment by ghostry** [comment]
I use google translate.
I do not speak English, but I will php. 
I thought maybe give zpanel world of Zuodiangongxian, but it seems not so, I had to learn English.

**Comment by ghost** [comment]
Jacob you missed the other post I closed. Not getting at all the point here over this issue??

M B

**Comment by jacobgelling** [comment]
No I'm not really understanding what he's saying either haha.

**Comment by mokiding** [comment]
@jacobg830  see this :D
https://github.com/zpanel/zpanelx/issues/219
