### ISSUE TITLE
Update error on CentOS 6.7: "script only supports ZPanel on CentOS 6.x."

### ISSUE THREAD

**Issue by slrslr** [zpanel/installers#60]
wget https://raw.github.com/zpanel/installers/master/upgrade/CentOS-6_4/10_1_1.sh
sh 10_1_1.sh

Detected : CentOs  6.7  64
Sorry, this upgrade script only supports ZPanel on CentOS 6.x.

I am on 6.7 (final) - Linux 2.6.32-042

By updating i am trying to solve issue with apache virtualhost where http://serverIP started redirecting to the hosted website instead of zpanel login.

**Comment by PixsaOJ** [comment]
It appears that the script can not detect OS correctly.

edit 10_1_1.sh by any editor ( I am using nano )
`Ctrl + w` to find the string "_Sorry, this upgrade script only supports ZPanel on CentOS 6.x._"
and comment from `if` to `fi` by adding `#` to every line.
Save and run the script again and it will pass the check.

**Comment by slrslr** [comment]
thx, and i should do this for all CentOS 6.x (including 6.9) right?

**Comment by PixsaOJ** [comment]
Yes sir
